In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
L

array([0.90544834, 0.43737122, 0.1096337 , 0.17389988, 0.03234333,
       0.25898057, 0.55097827, 0.08449482, 0.55915102, 0.72410593,
       0.66671757, 0.32591602, 0.79833809, 0.89687677, 0.30728187,
       0.89328356, 0.61078409, 0.79286354, 0.33777818, 0.27615121,
       0.41285555, 0.11134045, 0.90335621, 0.58874532, 0.16956813,
       0.07452691, 0.44768466, 0.59383551, 0.11491033, 0.5517839 ,
       0.3694604 , 0.80666944, 0.55905885, 0.68192303, 0.60193048,
       0.60917268, 0.07483253, 0.24277042, 0.7601475 , 0.2261527 ,
       0.88595724, 0.47624688, 0.58437195, 0.67530864, 0.35982658,
       0.48855201, 0.48273461, 0.5375253 , 0.68330392, 0.37905726,
       0.8577514 , 0.13694728, 0.36107123, 0.4817628 , 0.71778972,
       0.63768864, 0.32265609, 0.18269392, 0.93542117, 0.30842494,
       0.17057199, 0.39707833, 0.01462587, 0.62557213, 0.38348015,
       0.23218659, 0.30943079, 0.59179601, 0.12532239, 0.1597491 ,
       0.57851632, 0.00155872, 0.87549888, 0.71398405, 0.10081

In [3]:
sum(L)

47.25270798396911

In [4]:
np.sum(L)

47.252707983969096

In [5]:
big_array = np.random.rand(1_000_000)
%timeit sum(big_array)
%timeit np.sum(big_array)

180 ms ± 3.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
416 µs ± 18.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

2.5095826968746238e-06

In [7]:
np.max(big_array)

0.9999997776079861

In [8]:
big_array.min()

2.5095826968746238e-06

In [9]:
big_array.max()

0.9999997776079861

In [10]:
big_array.sum()

499911.81135301164

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.prod(X)

0

In [16]:
np.prod(X + 1)

20922789888000

In [17]:
np.mean(X)

7.5

In [18]:
np.median(X)

7.5

In [19]:
np.percentile(big_array, q=50)

0.4996152186249029

In [20]:
np.median(big_array)

0.4996152186249029

In [21]:
np.percentile(big_array, q=100)

0.9999997776079861

In [22]:
np.max(big_array)

0.9999997776079861

In [23]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, percent))

2.5095826968746238e-06
0.2496992786262414
0.4996152186249029
0.7499786266721656
0.9999997776079861


In [24]:
np.var(big_array)

0.08343274997142727

In [25]:
np.std(big_array)

0.28884727793667586

In [2]:
x = np.random.normal(0, 1, size=1_000_000)

In [27]:
np.mean(x)

-0.000660723569166565

In [28]:
np.std(x)

0.9992076911292559

## arg

In [4]:
np.argmin(x)

744883

In [5]:
x[744883]

-4.623499316956488

In [6]:
np.min(x)

-4.623499316956488

In [7]:
np.argmax(x)

359532

In [8]:
x[359532]

4.71203190345623

In [9]:
np.max(x)

4.71203190345623

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(x)

In [13]:
x

array([ 9, 11,  1,  6,  3,  7,  4,  2, 12,  0, 13, 14, 10,  5,  8, 15])

In [14]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
x

array([ 9, 11,  1,  6,  3,  7,  4,  2, 12,  0, 13, 14, 10,  5,  8, 15])

In [16]:
x.sort()

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
X = np.random.randint(10, size=(4, 4))
X

array([[5, 5, 9, 1],
       [6, 7, 4, 1],
       [2, 2, 6, 9],
       [2, 2, 0, 4]])

In [19]:
np.sort(X)

array([[1, 5, 5, 9],
       [1, 4, 6, 7],
       [2, 2, 6, 9],
       [0, 2, 2, 4]])

In [20]:
np.sort(X, axis=1)

array([[1, 5, 5, 9],
       [1, 4, 6, 7],
       [2, 2, 6, 9],
       [0, 2, 2, 4]])

In [21]:
np.sort(X, axis=0)

array([[2, 2, 0, 1],
       [2, 2, 4, 1],
       [5, 5, 6, 4],
       [6, 7, 9, 9]])

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
np.random.shuffle(x)

In [24]:
x

array([13,  1,  4,  3, 10,  6, 14,  5,  9,  2, 12,  0,  8, 11, 15,  7])

In [25]:
np.argsort(x)

array([11,  1,  9,  3,  2,  7,  5, 15, 12,  8,  4, 13, 10,  0,  6, 14])

In [28]:
X

array([[5, 5, 9, 1],
       [6, 7, 4, 1],
       [2, 2, 6, 9],
       [2, 2, 0, 4]])

In [29]:
np.argsort(X, axis=1)

array([[3, 0, 1, 2],
       [3, 2, 0, 1],
       [0, 1, 2, 3],
       [2, 0, 1, 3]])

In [30]:
np.argsort(X, axis=0)

array([[2, 2, 3, 0],
       [3, 3, 1, 1],
       [0, 0, 2, 3],
       [1, 1, 0, 2]])

In [26]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  6,  5,  7,  9, 14, 12, 10,  8, 11, 15, 13])

In [27]:
np.argpartition(x, 3)

array([11,  1,  9,  3,  2,  5,  7, 15,  8,  6, 10,  4, 12, 13, 14,  0])

In [31]:
np.argpartition(X, 2, axis=1)

array([[3, 1, 0, 2],
       [3, 2, 0, 1],
       [0, 1, 2, 3],
       [2, 1, 0, 3]])

In [32]:
np.argpartition(X, 2, axis=0)

array([[2, 2, 3, 0],
       [3, 3, 1, 1],
       [0, 0, 2, 3],
       [1, 1, 0, 2]])