# Numpy(numerical Python)

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

参考資料
* [NumPy quickstart](https://numpy.org/devdocs/user/quickstart.html)
* [NumPy Beginner's guide](https://www.packtpub.com/product/numpy-beginner-s-guide-third-edition/9781785281969)

## 歴史

* 1995年、Numeric
* 2001年、SciPy -> Numarray
* 2005年、*Travis Oliphant*がNumarrayの特性をNumericに結合する
* 2006年、NumPy 1.0

## ndarray



> 実在のデータとデータを描写するメタデータより構造される  
> 基本的に実在のデータを変えない、その代わりメタデータをかえる

### 作成する

#### リストから

In [3]:
foo = np.array([2, 3, 4])
foo

array([2, 3, 4])

In [4]:
bar = np.array([(1.5, 2, 3), (4, 5, 6)])
bar

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
foobar = np.array([[1, 2], [3, 4]], dtype=complex) # タイプ指定
foobar

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#### zeros()

In [6]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ones()

In [2]:
np.ones(shape=(2, 3, 4), dtype=np.int16) # タイプ指定

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

#### triu()

In [3]:
np.triu(np.ones((3, 3)), 1)

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

#### eye()

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### diag()

In [5]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### empty()

In [8]:
np.empty((2, 3)) # 初期化されていない

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#### full()

In [4]:
np.full(shape=(3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [3]:
np.full(shape=(2, 3), fill_value=[1, 2, 3])

array([[1, 2, 3],
       [1, 2, 3]])

#### arange()

In [9]:
np.arange(10, 30, 5) # pythonのrange(start, end, step)と同じ、ただ戻り値はarray

array([10, 15, 20, 25])

In [5]:
[i for i in range(0, 1, 0.1)] # 浮動小数利用不可

TypeError: 'float' object cannot be interpreted as an integer

In [10]:
np.arange(0, 2, .3) # 浮動小数利用可能

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

#### linspace()

In [11]:
np.linspace(0, 2, 9) # 0から2まで、均等に九個の数字（２を含む）

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
np.linspace(0, 2*np.pi, 100) # 一気に沢山の数字を作成する時には非常に便利

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

#### fromfunction()

In [21]:
def f(x, y):
    return 10 * x + y

np.fromfunction(f, (5, 4), dtype=int)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

### random

#### integer

In [8]:
np.random.randint(0, 10)

5

In [9]:
np.random.randint(0, 10, size=10)

array([4, 9, 1, 2, 6, 2, 2, 8, 7, 1])

In [11]:
np.random.randint(low=0, high=1, size=10)  # highは含まれない

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 7, 6],
       [5, 5, 4, 6, 6],
       [7, 4, 7, 7, 7]])

#### seedの設定

In [15]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 7, 4, 7],
       [6, 7, 4, 4, 7],
       [5, 7, 6, 7, 4]])

In [16]:
np.random.randint(4, 8, size=(3, 5))　# seedを設定しないとき、毎回実行の結果が違う

array([[6, 6, 6, 5, 6],
       [5, 7, 7, 5, 6],
       [6, 4, 4, 5, 5]])

In [20]:
np.random.seed(666)  # seedを指定する
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [21]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))  # 結果が同じになる

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

#### float point number

In [22]:
np.random.random() # [0.0, 1.0)

0.2811684913927954

In [24]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [25]:
np.random.random((3, 5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [26]:
np.random.normal()

0.7760516793129695

In [27]:
np.random.normal(10, 100)

128.06359754812632

In [28]:
np.random.normal(0, 1, (3, 5))

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

### uniform

In [5]:
np.random.uniform(5, 15, 3)

array([14.73571844,  7.00757649, 14.35764489])

### randn

In [7]:
np.random.randn(2, 2) # 生成了`N(0,I)`的标准正态分布

array([[ 1.8495032 , -0.03020602],
       [ 0.7850836 , -1.00652969]])

### randint

In [8]:
# 可以指定生成随机整数的最小值最大值（不包含）和维度大小：
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
np.random.randint(low, high, size)

array([[14,  9],
       [12,  7]])

### choice

In [9]:
# 可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样：
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['b', 'c'], dtype='<U1')

### print

In [14]:
print(np.arange(6)) # 1d

[0 1 2 3 4 5]


In [15]:
print(np.arange(12).reshape(4, 3)) # 2d

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
print(np.arange(24).reshape(2, 3, 4)) # 3d

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [17]:
print(np.arange(100_000)) # 中のものは自動的に省略される

[    0     1     2 ... 99997 99998 99999]


In [19]:
# 強制的に全てをプリントしたい時は, `set_printoptions`を変える
import sys

np.set_printoptions(threshold=sys.maxsize)
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

### dtype

In [2]:
a = np.arange(5)
a.dtype # 32bitのPythonを利用する場合は"int32"になる

dtype('int64')

In [3]:
np.*info?

np.finfo
np.iinfo
np.info

In [4]:
np.iinfo(np.int64) #dtypeがint64の時の限界値を確認

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [5]:
np.finfo(np.float64) # dtypeがfloat64の時の限界値と解析度

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [6]:
a.dtype.itemsize # bytes数

8

In [7]:
a.dtype.str # 文字列表示, "<" -> 最下位のバイトが先にくる

'<i8'

In [8]:
np.sctypeDict # 全てのdata typeの名前

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'L': numpy.uint64,
 'longlong': numpy.longlong,
 'q': numpy.longlong,
 9: numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'Q': numpy.ulonglong,
 10: numpy.ulonglong,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float128,
 'g': numpy.float128,
 13: numpy.float128,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14:

In [9]:
np.int(42.0 + 1.j) # 複素数を整数や浮動小数点型へ変換できない

TypeError: can't convert complex to int

### shape

In [10]:
a.shape # ListじゃなくTuple

(5,)

In [11]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [12]:
m.shape

(2, 2)

### shapeを操作

In [24]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

> `flatten()`は常に新しいコピーを戻る  
> `raval()`は配列の*view*を戻るかも(メモリをシェア)

In [26]:
b.shape = (6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [28]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [31]:
b.resize((2, 12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [23]:
b.reshape(3, -1) # `-1`をdimensionとして使う際は自動的計算される

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

### Copies and Views

#### コピーしない

In [6]:
a = np.arange(12).reshape(3, 4)
b = a
b is a

True

In [7]:
c = a[:, ::2]

In [8]:
np.may_share_memory(a, c)

True

#### Viewもしくは浅いコピー

In [37]:
c = a.view()
print(f"{c is a =}")
print(f"{c.base is a =}")
print(f"{c.flags.owndata=}")

c is a =False
c.base is a =False
c.flags.owndata=False


In [38]:
c = c.reshape((2, 6))
a.shape # shapeに影響を与えない

(3, 4)

In [39]:
c[0, 4] = 1234
a # dataが変わられた

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [40]:
s = a[:, 1:3] # slicingはviewを戻る
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### 深いコピー

In [9]:
d = a.copy()
print(f"{d is a = }")
print(f"{d.base is a = }")

d is a = False
d.base is a = False


In [10]:
d[0, 0] = 9999
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.may_share_memory(a, d)

False

### Array attributes

In [68]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [69]:
b.ndim

2

In [70]:
b.size

24

In [71]:
b.itemsize

8

In [72]:
b.nbytes

192

In [73]:
b.size * b.itemsize

192

In [74]:
b.resize(6, 4)

In [75]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [77]:
a

array([0, 1, 2, 3, 4])

In [78]:
a.T # そのまま

array([0, 1, 2, 3, 4])

In [79]:
f = np.array([1.j + 1, 2.j +3])
f

array([1.+1.j, 3.+2.j])

In [80]:
f.real

array([1., 3.])

In [81]:
f.imag

array([1., 2.])

In [82]:
f.dtype

dtype('complex128')

In [83]:
f.dtype.str

'<c16'

In [84]:
g = np.arange(4).reshape(2, 2)
g

array([[0, 1],
       [2, 3]])

In [85]:
g.flat

In [87]:
for item in g.flat: print(item)

0
1
2
3


In [88]:
g.flat[2]

2

In [89]:
g.flat[[1, 3]]

array([1, 3])

In [90]:
g.flat = 7
g

array([[7, 7],
       [7, 7]])

In [91]:
g.flat[[1, 3]] = 1
g

array([[7, 1],
       [7, 1]])

### Convert

In [93]:
f

array([1.+1.j, 3.+2.j])

In [94]:
f.tolist()

[(1+1j), (3+2j)]

In [95]:
f.astype(int)

array([1, 3])

In [96]:
f.astype('complex')

array([1.+1.j, 3.+2.j])