In [34]:
import numpy as np
import matplotlib.pyplot as plt

In [35]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

### scikit-learnのkNNを使う

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [38]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [39]:
X_predict = x.reshape(1, -1)

In [40]:
X_predict

array([[8.09360732, 3.36573151]])

In [41]:
kNN_classifier.predict(X_predict)

array([1])

In [42]:
y_predict = kNN_classifier.predict(X_predict)

In [43]:
y_predict[0]

1

### scikit-learnのKNNを実現する

In [44]:
%run kNN.py

In [45]:
knn_clf = KNNClassifier(3)

In [46]:
knn_clf.fit(X_train, y_train)

KNN(self.k=3)

In [47]:
y_predict = knn_clf.predict(X_predict)

In [48]:
y_predict

array([1])

In [49]:
y_predict[0]

1