## 1."import this"だけじゃない

In [1]:
import antigravity

In [45]:
import __hello__

Hello world!


In [46]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## 2. ...

In [3]:
...

Ellipsis

In [7]:
print(type(...))
print(id(...)) # ...はellipsisクラスのsingleton
print(id(...))

<class 'ellipsis'>
4352958848
4352958848


In [8]:
bool(...)

True

### [使い道](https://stackoverflow.com/questions/772124/what-does-the-ellipsis-object-do)

In [10]:
# passとして使う
def foo():
    pass

def bar():
    ...

foo()
bar()

In [ ]:
# typingとして使う
from typing import Callable

def partial(func: Callable[..., str], *args) -> Callable[..., str]:
    # Body

[PEP484](https://www.python.org/dev/peps/pep-0484/#callable)

In [11]:
# Numpyでslice操作
import numpy as np

foo = np.arange(16).reshape(2, 2, 4)

foo

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
foo[:, :, 2]

array([[ 2,  6],
       [10, 14]])

In [12]:
foo[..., 2] # 同じ結果

array([[ 2,  6],
       [10, 14]])

In [ ]:
## 3. shellのendを真似したいなら...(使わないでください)

In [15]:
__builtins__.end = None


def my_abs(x):
    if x > 0:
        return x
    else:
        return -x
    end
end

print(my_abs(10))
print(my_abs(-10))

10
10


## 4. promptを自分で定義する

In [ ]:
```python
>>> import sys
>>> sys.ps1
'>>> '
>>> sys.ps2
'... '
>>> sys.ps3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sys' has no attribute 'ps3'
>>> sys.ps1 = "海賊王に俺はなる!>>>"
海賊王に俺はなる!>>>sys.ps2 = "肉~"
海賊王に俺はなる!>>>for i in range(2):
肉~     print("サンジ、腹減った")
肉~
サンジ、腹減った
サンジ、腹減った
海賊王に俺はなる!>>>
```

## 5.and & or

In [18]:
(2 or 3) * (5 and 6 and 7)

14

In [21]:
"" and "b" # andは左から右へスキャンして、最初のFalseを戻る


''

In [22]:
"a" and "b" # 全てTrueなら、最後の値を戻る

'b'

In [24]:
"" or "a" # orは左から右へスキャンして、最初のTrueを戻る

'a'

In [26]:
"" or [] or None or {} # 全てFalseなら、最後の値を戻る

{}

## 6. リストを結合する

In [67]:
a = [1, 2]
b = [3, 4]
c = [5, 6]
sum((a, b, c), [])

[1, 2, 3, 4, 5, 6]

In [28]:
[*a, *b, *c]

[1, 2, 3, 4, 5, 6]

In [29]:
from itertools import chain

list(chain(a, b, c))

[1, 2, 3, 4, 5, 6]

## 7. \[-5, 256]

In [30]:
a = -6
b = -6

c = -5
d = -5

print(a is b)
print(c is d)

False
True


> CPythonでは、\[-5, 256]間の整数は事前に定義されたオブジェクト  
> 他の数字と違う

## 8. 文字列のintern

In [33]:
s1 = "hello" # internと言うのは同じ文字列はメモリにただ一つ保存され
s2 = "hello"
s1 is s2

True

In [34]:
s3 = 'hell o' # スペースある場合は、internは起動しない
s4 = 'hell o'
s3 is s4

False

## 9. dict()と{}

In [40]:
timeit -n 1000000 -r 5 dict()

112 ns ± 4.2 ns per loop (mean ± std. dev. of 5 runs, 1000000 loops each)


In [41]:
timeit -n 1000000 -r 5 {}

21.6 ns ± 1.42 ns per loop (mean ± std. dev. of 5 runs, 1000000 loops each)


`{}`は`dict()`より早い

In [42]:
from dis import dis
dis("{}")

  1           0 BUILD_MAP                0
              2 RETURN_VALUE


In [44]:
dis('dict()')

  1           0 LOAD_NAME                0 (dict)
              2 CALL_FUNCTION            0
              4 RETURN_VALUE


## 10."e"と"е"

In [50]:
valuе = 12
print(value)

NameError: name 'value' is not defined

> 原因は上の"valuе"の"е"は普通の"e"ではない

In [52]:
ord("e")

101

In [53]:
ord("е")

1077

> 使い道？  
> いたずら！

## 11. "site"

In [55]:
import sys

sys.path

['/Users/maozhongfu/GitHub/Python',
 '/Users/maozhongfu/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles',
 '/Users/maozhongfu/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
 '',
 '/Users/maozhongfu/Library/Python/3.8/lib/python/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aeosa',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/extensions',
 '/Users/maozhongfu/.ipython',
 '/Users/maozhongfu/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/vscode_datascience_helpers/dataframes']

In [56]:
!python3 -m site

sys.path = [
    '/Users/maozhongfu/GitHub/Python',
    '/Users/maozhongfu/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles',
    '/Users/maozhongfu/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
    '/Users/maozhongfu/Library/Python/3.8/lib/python/site-packages',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aeosa',
]
USER_BASE: '/Users/maozhongfu/Library/Python/3.8' (exists)
USER_SITE: '/Users/maozhongfu/Library/Python/3.8/lib/python/site-packages' (exists)
ENABLE_USER_SITE: True


## 12. http server

```shell
cd <path> # シェアしたいフォルダまで移動
ipconfig # 自分のipを把握他人に教える
python3 -m http.server <port number> # port numberでサーバーを立ち上げる
# その後 "http://<ip adress>:<port number>"でアクセルできる
```

## 13. pydoc

```python
python3 -m pydoc -p <port number>
```

## 14. ":=" (python3.8以上)

### if..else..

In [73]:
age = 22
if age > 20:
    print("お酒を飲めてもいい")

お酒を飲めてもいい


In [74]:
if (age:=22) > 20:
    print("お酒を飲めてもいい")

お酒を飲めてもいい


### while

In [ ]:
file = open("demo.txt", "r")
while True:
    line = file.readline()
    if not line:
        break
    print(line.strip())

In [ ]:
file = open("demo.txt", "r")
while (line := file.readline()):
    print(line.strip())

### comprehension

In [ ]:
scores = [22,54,75,89]
valid_scores = [
   longFunction(n)
   for n in scores
   if longFunction(n) # longFunctionは2回実行される
]

In [ ]:
scores = [22,54,75,89]
valid_scores = [
   result for n in scores
   result := longFunction(n) # 一回だけ
]

In [ ]:
## 15. 