# Numpy(numerical Python)

In [1]:
import numpy as np

参考資料
* [NumPy quickstart](https://numpy.org/devdocs/user/quickstart.html)
* [NumPy Beginner's guide](https://www.packtpub.com/product/numpy-beginner-s-guide-third-edition/9781785281969)

## 歴史

* 1995年、Numeric
* 2001年、SciPy -> Numarray
* 2005年、*Travis Oliphant*がNumarrayの特性をNumericに結合する
* 2006年、NumPy 1.0

## ndarray



> 実在のデータとデータを描写するメタデータより構造される  
> 基本的に実在のデータを変えない、その代わりメタデータをかえる

### dtype

In [2]:
a = np.arange(5)
a.dtype # 32bitのPythonを利用する場合は"int32"になる

dtype('int64')

In [3]:
np.*info?

np.finfo
np.iinfo
np.info

In [4]:
np.iinfo(np.int64) #dtypeがint64の時の限界値を確認

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [5]:
np.finfo(np.float64) # dtypeがfloat64の時の限界値と解析度

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [6]:
a.dtype.itemsize # bytes数

8

In [7]:
a.dtype.str # 文字列表示, "<" -> 最下位のバイトが先にくる

'<i8'

In [8]:
np.sctypeDict # 全てのdata typeの名前

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'L': numpy.uint64,
 'longlong': numpy.longlong,
 'q': numpy.longlong,
 9: numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'Q': numpy.ulonglong,
 10: numpy.ulonglong,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float128,
 'g': numpy.float128,
 13: numpy.float128,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14:

In [9]:
np.int(42.0 + 1.j) # 複素数を整数や浮動小数点型へ変換できない

TypeError: can't convert complex to int

### shape

In [10]:
a.shape # ListじゃなくTuple

(5,)

In [11]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [12]:
m.shape

(2, 2)

### slicing and indexing

In [13]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
b[0, 0, 0]

0

In [15]:
b[:, 0, 0]

array([ 0, 12])

In [16]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
b[0, :, :] # 同じ効果

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b[0, ...] # 上の簡易版

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
b[0, 1, ::2] # steps

array([4, 6])

In [20]:
b[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [21]:
b[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [22]:
b[0, ::-1, -1] # negative indices

array([11,  7,  3])

### shapeを操作

In [24]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

> `flatten()`は常に新しいコピーを戻る  
> `raval()`は配列の*view*を戻るかも(メモリをシェア)

In [26]:
b.shape = (6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [28]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [31]:
b.resize((2, 12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### stacking

In [34]:
c = np.arange(9).reshape(3, 3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
d = c * 2
d

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### Horizontal

In [37]:
np.hstack((c, d))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [38]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

#### Vertical

In [39]:
np.vstack((c, d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [40]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### Depth

In [41]:
np.dstack((c, d))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

#### Column

In [42]:
oned = np.arange(2)
oned

array([0, 1])

In [43]:
twice_oned = 2 * oned
twice_oned

array([0, 2])

In [44]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [45]:
np.column_stack((c, d))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [46]:
np.column_stack((c, d)) == np.hstack((c, d))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

#### Row

In [48]:
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [49]:
np.row_stack((c, d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [50]:
np.row_stack((c, d)) == np.vstack((c, d))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Splitting

#### Horizontal

In [54]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
np.hsplit(c, 3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [56]:
np.split(c, 3, axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

#### Vertical

In [58]:
np.vsplit(c, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [59]:
np.split(c, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

#### Depth-wise

In [65]:
e = np.arange(27).reshape(3, 3, 3)
e

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
np.dsplit(e, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### Array attributes

In [68]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [69]:
b.ndim

2

In [70]:
b.size

24

In [71]:
b.itemsize

8

In [72]:
b.nbytes

192

In [73]:
b.size * b.itemsize

192

In [74]:
b.resize(6, 4)

In [75]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [77]:
a

array([0, 1, 2, 3, 4])

In [78]:
a.T # そのまま

array([0, 1, 2, 3, 4])

In [79]:
f = np.array([1.j + 1, 2.j +3])
f

array([1.+1.j, 3.+2.j])

In [80]:
f.real

array([1., 3.])

In [81]:
f.imag

array([1., 2.])

In [82]:
f.dtype

dtype('complex128')

In [83]:
f.dtype.str

'<c16'

In [84]:
g = np.arange(4).reshape(2, 2)
g

array([[0, 1],
       [2, 3]])

In [85]:
g.flat

In [87]:
for item in g.flat: print(item)

0
1
2
3


In [88]:
g.flat[2]

2

In [89]:
g.flat[[1, 3]]

array([1, 3])

In [90]:
g.flat = 7
g

array([[7, 7],
       [7, 7]])

In [91]:
g.flat[[1, 3]] = 1
g

array([[7, 1],
       [7, 1]])

### Convert

In [93]:
f

array([1.+1.j, 3.+2.j])

In [94]:
f.tolist()

[(1+1j), (3+2j)]

In [95]:
f.astype(int)

array([1, 3])

In [96]:
f.astype('complex')

array([1.+1.j, 3.+2.j])